### ISSUE TITLE
Unrelated question

### ISSUE THREAD

**Issue by ThirteenAG** [elishacloud/BloodRayne-2-Patch#1]
Hey, not sure how to get in touch with you directly, but wanted to ask if you'd be willing to check out The Godfather's video player crash on vista+, that works on windows xp. I kinda have some assumptions on why it crashes and I was able to "fix it" in a way that only sound works, without video and then there's apparently some windows shim that does the same, audio only and no crash.
If you're up for a challenge, maybe we can chat on steam or something.

**Comment by elishacloud** [comment]
@ThirteenAG, I will give it a try.  Can you open an issue on the [dxwrapper issues](https://github.com/elishacloud/dxwrapper/issues) page?
