### ISSUE TITLE
Option to use dgVoodoo2 instead of d3d8to9

### ISSUE THREAD

**Issue by nipkownix** [elishacloud/BloodRayne-2-Patch#6]
Would it be possible to achieve that? On my system, this game's cutscenes only work correctly when I use dgVoodoo2. With d3d8to9, the cutscenes are cropped like this:

![ss](https://user-images.githubusercontent.com/33870163/96048500-1acf5c80-0e4d-11eb-917d-cc70033e1b19.png)

**Comment by TP555** [comment]
Hi

just copy the d3d8.dll from x86 and overwrite this , but then you lost all new Feautures from the FSSA Patch , HD Textures etc.

but you can try with patch 1.0.8.0 with some Media Players i had no problems with MPC.
in the Launcher under Cut Scene TAB , do first install the new cutscene.dll
then do set the path , where is MPC installed , thats all  !

with ALT + X , you can the skip a Cutscene , when you want  !

https://github.com/clsid2/mpc-hc/releases/tag/1.9.8

A short Question, do you have either Light issues or pops ?
Look at my new Thread  !

**Comment by elishacloud** [comment]
dgVoodoo2 now supports DirectX9.  This BloodRayne 2 patch will convert the game to DirectX9, so you can just use the d3d9.dll from dgVoodoo2 if you want to us that also.  However, a better option may be to use [dxvk](https://github.com/doitsujin/dxvk).  This will allow you to update from DirectX9 to Vulkan.

**Comment by elishacloud** [comment]
I made some options to allow using other DirectX8 wrappers, like dgVoodoo2.

Here is the update:  [patch.zip](https://github.com/elishacloud/BloodRayne-2-Patch/files/5492422/patch.zip)

_Edit: you can modify the `d3d8.ini` file to change the settings._

_Edit 2: Removing comment about not working with dgVoodoo2._

**Comment by elishacloud** [comment]
This issue should be addressed now.  See comment in [issue #7](https://github.com/elishacloud/BloodRayne-2-Patch/issues/7#issuecomment-722724188) on how to use dgVoodoo2 + the BR2 FSAA Patch 1.666.

**Comment by nipkownix** [comment]
Awesome. Thanks again, Elisha.
